fileVersion: 1
id: "10"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  TEST:
    database: NICK_EDW
    schema: STG_DEV
  WORK:
    database: QA_DB
    schema: QA_DB_SCHEMA
name: New Environment
type: Environment
